name: Sync EPG XML

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 00:00 UTC 执行（北京时间为 08:00）
  workflow_dispatch:      # 支持手动触发

permissions:
  contents: write  # ✅ 允许工作流写入仓库内容

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download pp.xml
        run: |
          curl -L -o pp.xml https://epg.112114.xyz/pp.xml

      - name: Check if file changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add pp.xml
          if git diff --cached --quiet; then
            echo "No changes, skipping commit."
            exit 0
          fi
          git commit -m "Sync latest pp.xml from epg.112114.xyz"
          git push
